apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics
  labels:
    app: metrics
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: metrics
        imagePullPolicy: Always
        image: prometheus-json-exporter:latest
        env:
          - name: ENDPOINT_JSON
            valueFrom:
              secretKeyRef:
                name: metrics
                key: ENDPOINT_JSON
        volumeMounts:
        - name: volume-config
          mountPath: /app/config
        ports:
        - containerPort: 7979
      volumes:
      - name: volume-config
        configMap:
          name: config-metrics
